"""Inicial

Revision ID: 30060fe042e7
Revises: 
Create Date: 2022-11-24 21:08:49.371173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30060fe042e7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tipo_documento", schema=None) as batch_op:
        batch_op.create_unique_constraint("nome_unico_tipo_documento", ["nome"])

    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.create_unique_constraint("nome_unico_usuario", ["nome"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.drop_constraint("nome_unico_usuario", type_="unique")

    with op.batch_alter_table("tipo_documento", schema=None) as batch_op:
        batch_op.drop_constraint("nome_unico_tipo_documento", type_="unique")

    # ### end Alembic commands ###
